name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Grant permission for OIDC token exchange
      contents: read   # Allow reading repository contents

    steps:
      # Enable Debug Logging
      - name: Enable Debug Logging
        run: |
          echo "##[group]Enable Debugging"
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "##[endgroup]"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Azure Credentials using OIDC authentication
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      # Initialize Terraform with backend configuration
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # Terraform Apply (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      # Optional: Terraform Destroy (uncomment if needed)
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
      #   working-directory: terraform
