name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC token exchange
      contents: read

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Azure Login with OIDC
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # Terraform Apply (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
