name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Grant permission for OIDC token exchange
      contents: read   # Allow reading the repository contents

    steps:
      # Enable Debug Logging
      - name: Enable Debug Logging
        run: |
          echo "##[group]Enable Debugging"
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV  # Enable step debug for all steps
          echo "##[endgroup]"

      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Azure Credentials using OIDC authentication
      - name: Set up Azure Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}       # Client ID of the Azure AD app
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}       # Tenant ID of your Azure AD directory
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Subscription ID of your Azure account

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Specify the Terraform version you need

      # Initialize Terraform with S3 backend and Azure provider configuration
      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Specify the working directory where your Terraform files are located

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform  # Specify the working directory

      # Terraform Apply (auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform  # Specify the working directory

      # Optional: Terraform Destroy (uncomment if needed)
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
      #   working-directory: terraform  # Specify the working directory
